import {test,expect} from '@playwright/test';
import {addDays,today} from '../../src/lib/domain';
test('público → orçamento persistido → admin → pedido → calendário',async({page})=>{
 test.skip(process.env.E2E_ALLOW_WRITES!=='true','Habilite E2E_ALLOW_WRITES apenas com um banco exclusivo de testes.');
 const name=`E2E ${Date.now()}`;
 await page.goto('/orcamento');
 await page.getByLabel('Formatura',{exact:true}).check();await page.getByRole('button',{name:'Continuar'}).click();
 await page.getByLabel('Quantidade de camisetas').fill('30');await page.getByRole('button',{name:'Continuar'}).click();
 await page.getByLabel('Estampa frontal').check();await page.getByLabel('Como está a sua arte?').selectOption('CRIAR');await page.getByRole('button',{name:'Continuar'}).click();
 await page.getByLabel('Entrega desejada').fill(addDays(today(),30));await page.getByLabel('Data do evento',{exact:true}).fill(addDays(today(),40));
 await page.getByLabel('Seu nome').fill(name);await page.getByLabel('WhatsApp com DDD').fill('84999999999');await page.getByLabel('Cidade / UF').fill('Natal/RN');await page.getByLabel('Autorizo o uso').check();
 await page.getByRole('button',{name:'Calcular e salvar orçamento'}).click();await expect(page).toHaveURL(/\/orcamento\/resultado\/GAL-Q-\d+\?token=[a-f0-9]{64}/);
 const resultUrl=page.url();await expect(page.getByRole('link',{name:'Finalizar pelo WhatsApp'})).toHaveAttribute('href',/^https:\/\/wa.me\/5584999215556\?text=/);
 await page.reload();await expect(page.getByText(name,{exact:true})).toBeVisible();
 await page.goto(resultUrl.split('?')[0]);await expect(page.getByText('Esta página saiu de órbita.')).toBeVisible();
 await page.goto('/admin');await expect(page).toHaveURL(/\/admin\/login/);
 await page.getByLabel('E-mail',{exact:true}).fill(process.env.ADMIN_EMAIL!);await page.getByLabel('Senha',{exact:true}).fill(process.env.ADMIN_INITIAL_PASSWORD!);await page.getByRole('button',{name:'Entrar no painel'}).click();await expect(page).toHaveURL(/\/admin$/);
  await page.goto(`/admin/orcamentos?q=${encodeURIComponent(name)}`);await page.getByRole('link',{name:/^Abrir GAL-Q-/}).click();await expect(page.getByRole('heading',{name,exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Converter em pedido'}).click();await expect(page).toHaveURL(/\/admin\/pedidos\/[a-f0-9-]+/);
  await page.getByRole('combobox',{name:'Etapa',exact:true}).selectOption('ARTE_APROVADA');await page.getByRole('button',{name:'Salvar pedido'}).click();await expect(page.getByText('Pedido atualizado.')).toBeVisible();await page.reload();await expect(page.getByRole('combobox',{name:'Etapa',exact:true})).toHaveValue('ARTE_APROVADA');
 await page.goto(`/admin/calendario?month=${addDays(today(),30).slice(0,7)}`);await expect(page.getByRole('link').filter({hasText:`Entrega · ${name}`}).first()).toBeVisible();
});
test('API administrativa rejeita acesso sem sessão',async({request})=>{const response=await request.post('/api/admin',{headers:{Origin:process.env.APP_URL||'http://localhost:3000'},data:{action:'settings',data:{}}});expect(response.status()).toBe(401);});
test('mutações rejeitam origem externa',async({request})=>{const response=await request.post('/api/quotes',{headers:{Origin:'https://external.invalid'},data:{}});expect(response.status()).toBe(400);});
test('página inicial adapta a navegação para celular',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.getByRole('heading',{name:'Sua ideia. Sua turma. Sua galáxia.'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'.impeccable/review/mobile.png',fullPage:true});});
test('página inicial desktop preserva logo original',async({page})=>{await page.setViewportSize({width:1440,height:1000});await page.goto('/');await expect(page.getByAltText('Galáxia Camisetas').first()).toBeVisible();await page.screenshot({path:'.impeccable/review/desktop.png',fullPage:true});});
test('navegação por teclado acessa conteúdo e avança o orçamento',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.goto('/');
 await page.keyboard.press('Tab');
 await expect(page.getByRole('link',{name:'Pular para o conteúdo'})).toBeFocused();
 await page.keyboard.press('Enter');
 await expect(page).toHaveURL(/#main$/);
 await page.keyboard.press('Tab');
 await expect(page.getByRole('link',{name:'Monte seu orçamento'})).toBeFocused();
 await page.keyboard.press('Enter');
 await expect(page).toHaveURL(/\/orcamento$/);
 const firstEvent=page.getByRole('radio',{name:'Empresa e equipe',exact:true});
 for(let i=0;i<12&&!(await firstEvent.evaluate(el=>el===document.activeElement));i++)await page.keyboard.press('Tab');
 await expect(firstEvent).toBeFocused();
 const outline=await firstEvent.evaluate(el=>getComputedStyle(el).outlineStyle);
 expect(outline).not.toBe('none');
 await page.keyboard.press('ArrowDown');
 await expect(page.getByRole('radio',{name:'Formatura',exact:true})).toBeChecked();
 await page.keyboard.press('Tab');
 await expect(page.getByRole('button',{name:'Continuar'})).toBeFocused();
 await page.keyboard.press('Enter');
 await expect(page.getByRole('spinbutton',{name:/Quantidade de camisetas/})).toBeVisible();
 expect(await page.locator('html').getAttribute('lang')).toBe('pt-BR');
});
