import {notFound} from 'next/navigation';
import Link from 'next/link';
import {Check,MessageCircle,ArrowUpRight} from 'lucide-react';
import {PublicHeader,PublicFooter} from '@/components/brand';
import {query} from '@/lib/db';
import {code,money,dateLabel,labels,whatsappMessage} from '@/lib/domain';
import type {Quote} from '@/lib/types';
export const dynamic='force-dynamic';
export const metadata={title:'Seu orçamento',robots:{index:false,follow:false}};
export default async function Result({params,searchParams}:{params:Promise<{code:string}>;searchParams:Promise<{token?:string}>}){const route=await params;const {token}=await searchParams;if(!token||!/^[a-f0-9]{64}$/.test(token))notFound();const quote=(await query<Quote>('SELECT * FROM quotes WHERE public_token=$1',[token]))[0];if(!quote||code(quote.number)!==route.code)notFound();const d=quote.details,p=quote.pricing;const expired=new Date(quote.valid_until)<new Date();const message=(p.provisional?'ESTIMATIVA COM VALORES PROVISÓRIOS — confirmar tabela.\n':'')+whatsappMessage(quote.number,d,p);return <div className="public-world"><PublicHeader/><main id="main" className="result-wrap"><div className="result-heading"><span className="success-icon"><Check/></span><h1>Sua ideia já tem<br/>um próximo passo.</h1><p>Orçamento salvo. Agora vamos conversar sobre os detalhes.</p></div><div className="result-grid"><section className="paper"><div className="section-heading"><h2>{code(quote.number)}</h2><span className="status">{expired?'Validade encerrada':`Válido até ${dateLabel(quote.valid_until)}`}</span></div>{p.provisional&&<p className="notice">Valores provisórios, sujeitos à confirmação da tabela real pela equipe.</p>}<dl className="details"><div><dt>Cliente</dt><dd>{d.name}</dd></div><div><dt>WhatsApp</dt><dd>+{d.phone}</dd></div><div><dt>Cidade</dt><dd>{d.city}</dd></div><div><dt>Evento</dt><dd>{d.event}</dd></div><div><dt>Modelo</dt><dd>{p.model.name}</dd></div><div><dt>Quantidade</dt><dd>{d.quantity} peças</dd></div><div><dt>Personalização</dt><dd>{p.prints.map(x=>x.name).join(', ')||'Sem estampa'}</dd></div><div><dt>Arte</dt><dd>{labels[d.art]}</dd></div><div><dt>Entrega desejada</dt><dd>{dateLabel(d.deliveryDate)}</dd></div><div><dt>Data do evento</dt><dd>{dateLabel(d.eventDate)}</dd></div></dl>{d.notes&&<div className="notes"><h3>Suas observações</h3><p>{d.notes}</p></div>}</section><aside className="paper price-summary"><h2>Seu orçamento</h2><dl><div><dt>{d.quantity} × {money(p.unitCents)}</dt><dd>{money(p.subtotalCents)}</dd></div><div><dt>Desconto ({p.discountPercent}%)</dt><dd>− {money(p.discountCents)}</dd></div><div><dt>Criação de arte</dt><dd>{money(p.artCents)}</dd></div><div className="total"><dt>Total {p.provisional?'provisório':''}</dt><dd>{money(p.totalCents)}</dd></div></dl><p>Frete não incluído. Cores, tamanhos, arte e prazo sujeitos à confirmação.</p>{expired&&<p className="notice">Este orçamento venceu. Peça a atualização dos valores no atendimento.</p>}<a href={`https://wa.me/${p.whatsapp}?text=${encodeURIComponent(message)}`} target="_blank" rel="noopener noreferrer" className="button whatsapp"><MessageCircle size={20}/> Finalizar pelo WhatsApp</a><small>Seu orçamento já está com a equipe. Guarde este link privado para consultar novamente.</small><Link href="/orcamento" className="text-link">Criar outro orçamento <ArrowUpRight size={16}/></Link></aside></div></main><PublicFooter/></div>;}
