import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';
import {Pool} from 'pg';
import nextEnv from '@next/env';
import {addDays,today} from '../../src/lib/domain';
import type {QuoteInput,Quote} from '../../src/lib/types';
nextEnv.loadEnvConfig(process.cwd());
const url=process.env.DATABASE_TEST_URL;
if(!url)throw new Error('Configure DATABASE_TEST_URL para um banco PostgreSQL exclusivo de testes.');
if(url===process.env.DATABASE_URL)throw new Error('O banco de teste deve ser diferente do banco operacional.');
const schema='test_'+randomUUID().replaceAll('-','');
const rootPool=new Pool({connectionString:url});
await rootPool.query(`CREATE SCHEMA "${schema}"`);
const scoped=new URL(url);scoped.searchParams.set('options',`-c search_path=${schema}`);process.env.DATABASE_URL=scoped.toString();
const {pool,query}=await import('../../src/lib/db');
const {createQuote,convertQuote,getSettings}=await import('../../src/lib/repository');
const {rateLimit}=await import('../../src/lib/auth');
const {quoteSchema,settingsSchema}=await import('../../src/lib/validation');
const adminId=randomUUID();
const base:QuoteInput={requestKey:randomUUID(),event:'Integração',modelId:'tradicional',quantity:30,printIds:['frente'],art:'CRIAR',eventDate:addDays(today(),40),deliveryDate:addDays(today(),30),name:'Cliente de teste',phone:'5584999999901',city:'Natal/RN',notes:'Somente banco de teste',consent:true};
test.before(async()=>{for(const name of (await readdir('db/migrations')).filter(n=>n.endsWith('.sql')).sort())await query(await readFile(`db/migrations/${name}`,'utf8'));await query('INSERT INTO administrators(id,email,password_hash) VALUES($1,$2,$3)',[adminId,'test@example.com','test-hash']);});
test.after(async()=>{await pool.end();await rootPool.query(`DROP SCHEMA "${schema}" CASCADE`);await rootPool.end();});
test('validação rejeita entrada manipulada e ativação sem catálogo',()=>{assert.equal(quoteSchema.safeParse({...base,quantity:-1}).success,false);assert.equal(quoteSchema.safeParse({...base,consent:false}).success,false);assert.equal(quoteSchema.safeParse({...base,phone:'123'}).success,false);assert.equal(settingsSchema.safeParse({enabled:true,provisional:false,whatsapp:'',minimumQuantity:10,productionDays:15,validityDays:7,artFeeCents:0,models:[],prints:[],discounts:[]}).success,false);});
test('retry concorrente persiste exatamente um orçamento e um cliente',async()=>{const [a,b]=await Promise.all([createQuote(base),createQuote(base)]);assert.equal(a.id,b.id);assert.equal((await query('SELECT id FROM quotes WHERE request_key=$1',[base.requestKey])).length,1);assert.equal((await query('SELECT id FROM customers WHERE phone=$1',[base.phone])).length,1);assert.equal(a.total_cents,141950);});
test('mesma chave com dados alterados nunca retorna o orçamento anterior silenciosamente',async()=>{const input={...base,requestKey:randomUUID()};await createQuote(input);await assert.rejects(()=>createQuote({...input,quantity:50}),/outros dados/);});
test('alterações do catálogo não alteram snapshot persistido',async()=>{const quote=await createQuote({...base,requestKey:randomUUID()});const settings=await getSettings();await query('UPDATE settings SET data=$1 WHERE id=1',[JSON.stringify({...settings,models:settings.models.map(m=>({...m,priceCents:9999}))})]);const stored=(await query<Quote>('SELECT * FROM quotes WHERE id=$1',[quote.id]))[0];assert.equal(stored.pricing.model.priceCents,3500);await query('UPDATE settings SET data=$1 WHERE id=1',[JSON.stringify(settings)]);});
test('conversão concorrente cria apenas um pedido e aprova orçamento',async()=>{const quote=await createQuote({...base,requestKey:randomUUID()});const [a,b]=await Promise.all([convertQuote(quote.id,adminId),convertQuote(quote.id,adminId)]);assert.equal(a,b);assert.equal((await query('SELECT id FROM orders WHERE quote_id=$1',[quote.id])).length,1);assert.equal((await query<Quote>('SELECT * FROM quotes WHERE id=$1',[quote.id]))[0].status,'APROVADO');});
test('orçamento vencido não pode virar pedido',async()=>{const quote=await createQuote({...base,requestKey:randomUUID()});await query("UPDATE quotes SET valid_until=now()-interval '1 day' WHERE id=$1",[quote.id]);await assert.rejects(()=>convertQuote(quote.id,adminId),/vencido/);assert.equal((await query('SELECT id FROM orders WHERE quote_id=$1',[quote.id])).length,0);});
test('tentativas de autenticação são limitadas atomicamente no PostgreSQL',async()=>{const key=randomUUID();const results=await Promise.all(Array.from({length:12},()=>rateLimit(key,8,15)));assert.equal(results.filter(Boolean).length,8);});
