'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {Check,ArrowRight} from 'lucide-react';
import {canTransition,labels,orderStatuses,today} from '@/lib/domain';
export async function mutate(payload:unknown){const response=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error);return result;}
export function MutationButton({payload,children,className='button',redirectTo}:{payload:unknown;children:React.ReactNode;className?:string;redirectTo?:string}){const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState('');async function run(){setBusy(true);setError('');try{const result=await mutate(payload);if(redirectTo)router.push(redirectTo.replace(':id',result.id));router.refresh();}catch(error){setError((error as Error).message);}finally{setBusy(false);}}return <div><button onClick={run} className={className} disabled={busy}>{busy?'Salvando…':children}</button>{error&&<p role="alert" className="form-error">{error}</p>}</div>;}
export function QuoteControls({id,status}:{id:string;status:string}){const router=useRouter();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError('');setMessage('');try{await mutate({action:'quote-status',id,status:form.get('status')});setMessage('Status atualizado.');router.refresh();}catch(error){setError((error as Error).message);}finally{setBusy(false);}}return <div className="stack"><h2>Próximo passo</h2>{status!=='APROVADO'?<><form className="stack" onSubmit={submit}><label>Status do atendimento<select name="status" defaultValue={status}>{['NOVO','EM_CONTATO','PERDIDO'].map(s=><option value={s} key={s}>{labels[s]}</option>)}</select></label><button className="button secondary" disabled={busy}>Salvar status</button></form><MutationButton payload={{action:'convert',id}} redirectTo="/admin/pedidos/:id">Converter em pedido <ArrowRight size={18}/></MutationButton><RenewForm id={id}/></>:<p>Este orçamento já foi convertido em pedido.</p>}{error&&<p role="alert" className="form-error">{error}</p>}{message&&<p role="status">{message}</p>}</div>;}
function RenewForm({id}:{id:string}){const router=useRouter();const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);return <form className="stack compact-form" onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);setBusy(true);try{await mutate({action:'renew',id,date:data.get('date')});setMessage('Validade atualizada, mantendo o preço registrado.');router.refresh();}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}}><label>Renovar validade mantendo o preço<input type="date" name="date" min={today()} required/></label><button disabled={busy} className="button ghost">Renovar validade</button>{message&&<p role="status">{message}</p>}</form>;}
export function FollowupForm({id}:{id:string}){const router=useRouter();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');return <form className="stack" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);setBusy(true);try{await mutate({action:'followup',id,dueAt:new Date(String(data.get('due'))).toISOString(),note:data.get('note')});form.reset();setMessage('Retorno agendado.');router.refresh();}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}}><h2>Agendar retorno</h2><label>Quando entrar em contato<input type="datetime-local" name="due" required/></label><label>O que precisamos conversar?<textarea name="note" rows={3} required maxLength={1000}/></label><button disabled={busy} className="button secondary">{busy?'Agendando…':'Agendar follow-up'}</button>{message&&<p role="status">{message}</p>}</form>;}
export function OrderForm({id,status,deliveryDate,notes}:{id:string;status:string;deliveryDate:string;notes:string}){const router=useRouter();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const closed=['ENTREGUE','CANCELADO'].includes(status);return <form className="stack" onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);setBusy(true);setMessage('');try{await mutate({action:'order',id,status:data.get('status'),deliveryDate:data.get('deliveryDate'),notes:data.get('notes')});setMessage('Pedido atualizado.');router.refresh();}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}}><h2>Acompanhar produção</h2><label>Etapa<select name="status" defaultValue={status} key={status}>{orderStatuses.filter(s=>s===status||canTransition(status,s)).map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label>{closed&&<p className="hint">Pedido encerrado. Você pode atualizar as observações.</p>}<label>Data combinada para entrega<input type="date" name="deliveryDate" defaultValue={deliveryDate} required readOnly={closed}/></label><label>Observações da produção<textarea name="notes" rows={5} defaultValue={notes} maxLength={4000}/></label><button className="button" disabled={busy}>{busy?'Salvando…':'Salvar pedido'}<Check size={18}/></button>{message&&<p role="status">{message}</p>}</form>;}
