'use client';
import {useState,useRef} from 'react';
import {ArrowLeft,ArrowRight,Check,Shirt} from 'lucide-react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {addDays,today,money} from '@/lib/domain';
import type {Settings,QuoteInput} from '@/lib/types';
const steps=['Seu evento','A camiseta','Personalização','Prazo e contato'];
export function QuoteForm({settings}:{settings:Settings}){
 const router=useRouter();const form=useRef<HTMLFormElement>(null);const [step,setStep]=useState(0);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const [data,setData]=useState<QuoteInput>({requestKey:'',event:'',modelId:settings.models[0]?.id??'',quantity:settings.minimumQuantity,printIds:[],art:'PRONTA',eventDate:'',deliveryDate:'',name:'',phone:'',city:'',notes:'',consent:false});
 const set=<K extends keyof QuoteInput>(key:K,value:QuoteInput[K])=>setData(current=>({...current,[key]:value}));
 async function submit(event:React.FormEvent){event.preventDefault();setError('');if(step<3){setStep(step+1);return;}setBusy(true);try{const requestKey=data.requestKey||crypto.randomUUID();set('requestKey',requestKey);const response=await fetch('/api/quotes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,requestKey})});const result=await response.json();if(!response.ok)throw new Error(result.error);router.push(result.url);}catch(error){setError(error instanceof Error?error.message:'Não conseguimos salvar. Tente novamente.');setBusy(false);}}
 return <div className="quote-workspace"><aside className="quote-progress"><ol>{steps.map((label,index)=><li key={label} className={index===step?'active':index<step?'complete':''}><span>{index<step?<Check size={16}/>:index+1}</span><div>{label}<small>{index===step?'Você está aqui':index<step?'Concluído':'Próxima etapa'}</small></div></li>)}</ol><p>Seu orçamento será salvo antes de abrir o WhatsApp.</p></aside><form ref={form} className="quote-form" onSubmit={submit}>
 <div className="step-top"><span>Etapa {step+1} de 4</span><span>Feito para a sua ideia</span></div>
 {settings.provisional&&<p className="notice">Tabela provisória: os valores são estimativas de demonstração e precisam ser confirmados pela equipe.</p>}
 {step===0&&<fieldset><legend>Qual é a ocasião?</legend><p className="field-intro">Toda turma tem uma história. Qual é a sua?</p><div className="choice-grid">{['Empresa e equipe','Formatura','Aniversário','Evento esportivo','Igreja e comunidade','Outro evento'].map(value=><label className={`choice ${data.event===value?'selected':''}`} key={value}><input type="radio" name="event" value={value} checked={data.event===value} onChange={()=>set('event',value)} required/><span>{value}</span></label>)}</div></fieldset>}
 {step===1&&<fieldset><legend>A base da sua criação</legend><p className="field-intro">Escolha o modelo e o tamanho da sua turma.</p><div className="model-list">{settings.models.map(model=><label className={`choice model ${data.modelId===model.id?'selected':''}`} key={model.id}><input type="radio" name="model" checked={data.modelId===model.id} onChange={()=>set('modelId',model.id)} required/><Shirt size={32}/><span>{model.name}<small>Base por peça</small></span><strong>{money(model.priceCents)}</strong></label>)}</div><label>Quantidade de camisetas<input type="number" min={settings.minimumQuantity} max={10000} required value={data.quantity} onChange={e=>set('quantity',Number(e.target.value))}/><small>Mínimo de {settings.minimumQuantity} peças.</small></label>{settings.discounts.length>0&&<p className="hint">Desconto por volume: {settings.discounts.map(d=>`${d.percent}% a partir de ${d.from} peças`).join(' · ')}.</p>}</fieldset>}
 {step===2&&<fieldset><legend>Agora, a sua personalidade.</legend><p className="field-intro">Os adicionais abaixo são cobrados por camiseta.</p><div className="choice-grid">{settings.prints.map(print=><label className={`choice ${data.printIds.includes(print.id)?'selected':''}`} key={print.id}><input type="checkbox" checked={data.printIds.includes(print.id)} onChange={e=>{set('printIds',e.target.checked?[...data.printIds,print.id]:data.printIds.filter(id=>id!==print.id));if(e.target.checked&&data.art==='SEM_ARTE')set('art','PRONTA');}}/><span>{print.name}<small>+ {money(print.priceCents)} / peça</small></span></label>)}</div><label>Como está a sua arte?<select value={data.art} onChange={e=>{const art=e.target.value as QuoteInput['art'];set('art',art);if(art==='SEM_ARTE')set('printIds',[]);}}><option value="PRONTA">Já tenho uma arte</option><option value="CRIAR">Preciso criar uma arte (+ {money(settings.artFeeCents)})</option><option value="SEM_ARTE">Quero camisetas sem estampa</option></select></label><p className="hint">O arquivo da arte será combinado com a equipe pelo WhatsApp.</p></fieldset>}
 {step===3&&<fieldset><legend>Quase pronto para decolar.</legend><p className="field-intro">Defina o prazo e diga como podemos falar com você.</p><div className="form-grid"><label>Entrega desejada<input type="date" required min={addDays(today(),settings.productionDays)} value={data.deliveryDate} onChange={e=>set('deliveryDate',e.target.value)}/></label><label>Data do evento<input type="date" required min={data.deliveryDate||addDays(today(),settings.productionDays)} value={data.eventDate} onChange={e=>set('eventDate',e.target.value)}/></label><label>Seu nome<input autoComplete="name" required maxLength={120} value={data.name} onChange={e=>set('name',e.target.value)}/></label><label>WhatsApp com DDD<input type="tel" autoComplete="tel" required placeholder="(84) 99999-9999" maxLength={20} value={data.phone} onChange={e=>set('phone',e.target.value)}/></label><label className="full">Cidade / UF<input autoComplete="address-level2" required maxLength={120} value={data.city} onChange={e=>set('city',e.target.value)}/></label><label className="full">Algo mais que devemos saber? <small>Opcional</small><textarea rows={3} maxLength={2000} value={data.notes} onChange={e=>set('notes',e.target.value)}/></label></div><p className="hint">Prazo mínimo: {settings.productionDays} dias corridos. Tamanhos, cores, frete e disponibilidade serão confirmados no atendimento.</p><label className="check-line"><input type="checkbox" required checked={data.consent} onChange={e=>set('consent',e.target.checked)}/><span>Autorizo o uso destes dados para preparar meu orçamento e entrar em contato. <Link href="/privacidade" target="_blank">Saiba como cuidamos dos dados.</Link></span></label></fieldset>}
 {error&&<div><p role="alert" className="form-error">{error}</p>{error.includes('outros dados')&&<button type="button" className="button secondary" onClick={()=>{set('requestKey',crypto.randomUUID());setError('');}}>Preparar novo orçamento com estas alterações</button>}</div>}<div className="form-actions">{step>0?<button className="button ghost" type="button" disabled={busy} onClick={()=>{setStep(step-1);setError('');}}><ArrowLeft size={18}/> Voltar</button>:<span/>}<button className="button" type="submit" disabled={busy}>{busy?'Salvando seu orçamento…':step===3?'Calcular e salvar orçamento':'Continuar'}{!busy&&<ArrowRight size={18}/>}</button></div>
 </form></div>;
}
